<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: eugene
 * Date: Fri, 09 Mar 2018 17:58:57 -0600
 */

$conf['title'] = 'AA Affordable Realty';
$conf['start'] = 'home';
$conf['template'] = 'aaaffordablerealty';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['tocminheads'] = '0';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,recent,revisions,search,register,rss,subscribe,unsubscribe,source,export_raw';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['jquerycdn'] = 'cdnjs';
$conf['tpl']['aaaffordablerealty']['discussionPage'] = '';

// end auto-generated content
