# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 01 Mar 2018 02:26:51 +0000
*               @ALL          1
*               @user         8
